### ISSUE TITLE
missing chat template when querying open-sourced models

### ISSUE THREAD

**Issue by wangruohui** [declare-lab/red-instruct#5]
Hi, 

I am reading your code and found that the code does not apply chat template [before tokenization](https://github.com/declare-lab/red-instruct/blob/main/generate_responses.py#L227C29-L227C35), e.g. `[INST]` and `[\INST]` for llama2 (see https://huggingface.co/docs/transformers/chat_templating for reference). 

It seems this template is important for the model to give safe response. When they appear in the input, model will more probably response safely. 

Would you consider applying the chat template and re-evaluate the ASR?

**Comment by Bhardwaj-Rishabh** [comment]
Thanks for the suggestion, yes at that time, chat templating was not very clear and the Llama-2-FT results included in the paper are based on the model from NousResearch/Nous-Hermes-llama-2-7b. It uses a different template than Llama-2-chat template from Meta. We will edit the code by including chat templates.

Update: Added chat templates, will test the suitability of the implementation on a larger set of models soon.
