### ISSUE TITLE
api_key

### ISSUE THREAD

**Issue by richhh520** [declare-lab/red-instruct#6]
Dear author,

I'm sorry that I cannot find parameters such as "api_base", "api_version" and "api_type". Where to find these? Thanks a lot.

Best wishes.

**Comment by richhh520** [comment]
I just delete these paramters. seems it works.

**Comment by Bhardwaj-Rishabh** [comment]
Yes, it depends on the subscription and open ai API version, we use it via azure.

**Comment by HITLittleZheng** [comment]
I use the API for chatgpt.But I cannot find parameters such as "model_engine" and "model_family". What should I put in these two parameters?

**Comment by HITLittleZheng** [comment]
> I just delete these paramters. seems it works.

I use the API for chatgpt.But I cannot find parameters such as "model_engine" and "model_family". What should I put in these two parameters?
