### ISSUE TITLE
Is it possible to use chatgpt's API instead of gpt4's?

### ISSUE THREAD

**Issue by HITLittleZheng** [declare-lab/red-instruct#7]
Dear author,
in performing the second step, I don't have the API for gpt4, can I use the API for chatgpt instead?

**Comment by Bhardwaj-Rishabh** [comment]
Yes, why not. In our experiments, when compared against ChatGPT4, ChatGPT3.5 is slightly less accurate as a judge so I would suggest manually verifying a few annotations before running it for large-scale experiments.
